// =============================================================================
// Walmart Global Enterprise Demo Seed Constants
// Standardized on US Dollars ($ USD) across 10 top countries and 120 stores.
// =============================================================================

import { Prisma } from "@prisma/client";

/** Shorthand for creating Prisma Decimal values */
export const D = (v: string | number) => new Prisma.Decimal(String(v));

/** Organization */
export const ORG_ID = "org-walmart-demo";
export const ORG = {
  id: ORG_ID,
  name: "Walmart Global Enterprise",
  code: "WALMART-GLOBAL",
  currency: "USD",
  timezone: "America/New_York",
};

/** Demo admin user (required for AuditLog.userId FK) */
export const ADMIN_USER_ID = "user-demo-admin";

/** Admin role */
export const ADMIN_ROLE_ID = "role-demo-admin";

/** Regions: 10 Top Countries */
export const REGIONS = [
  {
    "id": "region-usa",
    "name": "United States",
    "code": "USA"
  },
  {
    "id": "region-can",
    "name": "Canada",
    "code": "CAN"
  },
  {
    "id": "region-gbr",
    "name": "United Kingdom",
    "code": "GBR"
  },
  {
    "id": "region-deu",
    "name": "Germany",
    "code": "DEU"
  },
  {
    "id": "region-jpn",
    "name": "Japan",
    "code": "JPN"
  },
  {
    "id": "region-ind",
    "name": "India",
    "code": "IND"
  },
  {
    "id": "region-mex",
    "name": "Mexico",
    "code": "MEX"
  },
  {
    "id": "region-chn",
    "name": "China",
    "code": "CHN"
  },
  {
    "id": "region-bra",
    "name": "Brazil",
    "code": "BRA"
  },
  {
    "id": "region-aus",
    "name": "Australia",
    "code": "AUS"
  }
] as const;

/** Stores: 120 Stores across 10 Top Countries (12 stores per country) */
export const STORES = [
  {
    "id": "store-001",
    "regionId": "region-usa",
    "code": "WAL-USA-001",
    "name": "Walmart Supercenter Bentonville HQ",
    "address": "702 SW 8th St",
    "city": "Bentonville",
    "state": "Arkansas",
    "country": "United States",
    "pincode": "72716",
    "phone": "+1 555 1001",
    "email": "bentonville.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 36.3729,
    "longitude": -94.2088,
    "status": "ACTIVE"
  },
  {
    "id": "store-002",
    "regionId": "region-usa",
    "code": "WAL-USA-002",
    "name": "Walmart Manhattan Supercenter",
    "address": "500 8th Ave",
    "city": "New York",
    "state": "New York",
    "country": "United States",
    "pincode": "10018",
    "phone": "+1 555 1002",
    "email": "newyork.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 40.7527,
    "longitude": -73.9934,
    "status": "ACTIVE"
  },
  {
    "id": "store-003",
    "regionId": "region-usa",
    "code": "WAL-USA-003",
    "name": "Walmart Supercenter Los Angeles",
    "address": "2000 N Highland Ave",
    "city": "Los Angeles",
    "state": "California",
    "country": "United States",
    "pincode": "90068",
    "phone": "+1 555 1003",
    "email": "losangeles.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 34.1083,
    "longitude": -118.3387,
    "status": "ACTIVE"
  },
  {
    "id": "store-004",
    "regionId": "region-usa",
    "code": "WAL-USA-004",
    "name": "Walmart Supercenter Chicago West",
    "address": "4650 W North Ave",
    "city": "Chicago",
    "state": "Illinois",
    "country": "United States",
    "pincode": "60639",
    "phone": "+1 555 1004",
    "email": "chicago.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 41.9097,
    "longitude": -87.7431,
    "status": "ACTIVE"
  },
  {
    "id": "store-005",
    "regionId": "region-usa",
    "code": "WAL-USA-005",
    "name": "Walmart Supercenter Houston Galleria",
    "address": "2727 Dunvale Rd",
    "city": "Houston",
    "state": "Texas",
    "country": "United States",
    "pincode": "77063",
    "phone": "+1 555 1005",
    "email": "houston.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 29.7348,
    "longitude": -95.5135,
    "status": "ACTIVE"
  },
  {
    "id": "store-006",
    "regionId": "region-usa",
    "code": "WAL-USA-006",
    "name": "Walmart Supercenter Phoenix Metro",
    "address": "5250 W Indian School Rd",
    "city": "Phoenix",
    "state": "Arizona",
    "country": "United States",
    "pincode": "85031",
    "phone": "+1 555 1006",
    "email": "phoenix.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 33.4942,
    "longitude": -112.1729,
    "status": "ACTIVE"
  },
  {
    "id": "store-007",
    "regionId": "region-usa",
    "code": "WAL-USA-007",
    "name": "Walmart Supercenter Dallas North",
    "address": "1521 N Cockrell Hill Rd",
    "city": "Dallas",
    "state": "Texas",
    "country": "United States",
    "pincode": "75211",
    "phone": "+1 555 1007",
    "email": "dallas.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 32.7712,
    "longitude": -96.8967,
    "status": "ACTIVE"
  },
  {
    "id": "store-008",
    "regionId": "region-usa",
    "code": "WAL-USA-008",
    "name": "Walmart Supercenter Miami Midtown",
    "address": "3200 NW 79th St",
    "city": "Miami",
    "state": "Florida",
    "country": "United States",
    "pincode": "33147",
    "phone": "+1 555 1008",
    "email": "miami.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 25.8471,
    "longitude": -80.2505,
    "status": "ACTIVE"
  },
  {
    "id": "store-009",
    "regionId": "region-usa",
    "code": "WAL-USA-009",
    "name": "Walmart Supercenter Seattle South",
    "address": "743 Rainier Ave S",
    "city": "Seattle",
    "state": "Washington",
    "country": "United States",
    "pincode": "98144",
    "phone": "+1 555 1009",
    "email": "seattle.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 47.5946,
    "longitude": -122.3099,
    "status": "ACTIVE"
  },
  {
    "id": "store-010",
    "regionId": "region-usa",
    "code": "WAL-USA-010",
    "name": "Walmart Supercenter Atlanta Midtown",
    "address": "835 Martin Luther King Jr Dr NW",
    "city": "Atlanta",
    "state": "Georgia",
    "country": "United States",
    "pincode": "30314",
    "phone": "+1 555 1010",
    "email": "atlanta.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 33.7537,
    "longitude": -84.4158,
    "status": "ACTIVE"
  },
  {
    "id": "store-011",
    "regionId": "region-usa",
    "code": "WAL-USA-011",
    "name": "Walmart Supercenter Denver Central",
    "address": "7800 E Smith Rd",
    "city": "Denver",
    "state": "Colorado",
    "country": "United States",
    "pincode": "80207",
    "phone": "+1 555 1011",
    "email": "denver.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 39.7712,
    "longitude": -104.8964,
    "status": "ACTIVE"
  },
  {
    "id": "store-012",
    "regionId": "region-usa",
    "code": "WAL-USA-012",
    "name": "Walmart Supercenter Boston Metro",
    "address": "300 Commercial St",
    "city": "Boston",
    "state": "Massachusetts",
    "country": "United States",
    "pincode": "02109",
    "phone": "+1 555 1012",
    "email": "boston.store@walmart.com",
    "image": "/images/stores/store-usa.webp",
    "latitude": 42.3656,
    "longitude": -71.0543,
    "status": "ACTIVE"
  },
  {
    "id": "store-013",
    "regionId": "region-can",
    "code": "WAL-CAN-013",
    "name": "Walmart Toronto Downtown",
    "address": "900 Dufferin St",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "pincode": "M6H 4B1",
    "phone": "+1 555 1013",
    "email": "toronto.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 43.6561,
    "longitude": -79.4357,
    "status": "ACTIVE"
  },
  {
    "id": "store-014",
    "regionId": "region-can",
    "code": "WAL-CAN-014",
    "name": "Walmart Vancouver Grandview",
    "address": "3585 Grandview Hwy",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "pincode": "V5M 2G7",
    "phone": "+1 555 1014",
    "email": "vancouver.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 49.2577,
    "longitude": -123.0256,
    "status": "ACTIVE"
  },
  {
    "id": "store-015",
    "regionId": "region-can",
    "code": "WAL-CAN-015",
    "name": "Walmart Montreal Decarie",
    "address": "5400 Rue Jean-Talon O",
    "city": "Montreal",
    "state": "Quebec",
    "country": "Canada",
    "pincode": "H4P 2M7",
    "phone": "+1 555 1015",
    "email": "montreal.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 45.4984,
    "longitude": -73.6558,
    "status": "ACTIVE"
  },
  {
    "id": "store-016",
    "regionId": "region-can",
    "code": "WAL-CAN-016",
    "name": "Walmart Calgary East Hills",
    "address": "255 East Hills Blvd SE",
    "city": "Calgary",
    "state": "Alberta",
    "country": "Canada",
    "pincode": "T2A 8A5",
    "phone": "+1 555 1016",
    "email": "calgary.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 51.0427,
    "longitude": -113.9189,
    "status": "ACTIVE"
  },
  {
    "id": "store-017",
    "regionId": "region-can",
    "code": "WAL-CAN-017",
    "name": "Walmart Ottawa South Keys",
    "address": "2210 Bank St",
    "city": "Ottawa",
    "state": "Ontario",
    "country": "Canada",
    "pincode": "K1V 1J5",
    "phone": "+1 555 1017",
    "email": "ottawa.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 45.3621,
    "longitude": -75.6599,
    "status": "ACTIVE"
  },
  {
    "id": "store-018",
    "regionId": "region-can",
    "code": "WAL-CAN-018",
    "name": "Walmart Edmonton West Central",
    "address": "18521 Stony Plain Rd",
    "city": "Edmonton",
    "state": "Alberta",
    "country": "Canada",
    "pincode": "T5S 2V9",
    "phone": "+1 555 1018",
    "email": "edmonton.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 53.5412,
    "longitude": -113.6421,
    "status": "ACTIVE"
  },
  {
    "id": "store-019",
    "regionId": "region-can",
    "code": "WAL-CAN-019",
    "name": "Walmart Mississauga Heartland",
    "address": "800 Matheson Blvd W",
    "city": "Mississauga",
    "state": "Ontario",
    "country": "Canada",
    "pincode": "L5V 2N6",
    "phone": "+1 555 1019",
    "email": "mississauga.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 43.6074,
    "longitude": -79.6912,
    "status": "ACTIVE"
  },
  {
    "id": "store-020",
    "regionId": "region-can",
    "code": "WAL-CAN-020",
    "name": "Walmart Winnipeg Polo Park",
    "address": "1001 Empress St",
    "city": "Winnipeg",
    "state": "Manitoba",
    "country": "Canada",
    "pincode": "R3G 3H3",
    "phone": "+1 555 1020",
    "email": "winnipeg.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 49.8863,
    "longitude": -97.1994,
    "status": "ACTIVE"
  },
  {
    "id": "store-021",
    "regionId": "region-can",
    "code": "WAL-CAN-021",
    "name": "Walmart Quebec Sainte-Foy",
    "address": "1700 Rue Bouvier",
    "city": "Quebec City",
    "state": "Quebec",
    "country": "Canada",
    "pincode": "G2J 1A3",
    "phone": "+1 555 1021",
    "email": "quebeccity.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 46.8291,
    "longitude": -71.2821,
    "status": "ACTIVE"
  },
  {
    "id": "store-022",
    "regionId": "region-can",
    "code": "WAL-CAN-022",
    "name": "Walmart Hamilton Mountain",
    "address": "499 Mohawk Rd E",
    "city": "Hamilton",
    "state": "Ontario",
    "country": "Canada",
    "pincode": "L8V 4X4",
    "phone": "+1 555 1022",
    "email": "hamilton.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 43.2212,
    "longitude": -79.8654,
    "status": "ACTIVE"
  },
  {
    "id": "store-023",
    "regionId": "region-can",
    "code": "WAL-CAN-023",
    "name": "Walmart Brampton North",
    "address": "50 Quarry Edge Dr",
    "city": "Brampton",
    "state": "Ontario",
    "country": "Canada",
    "pincode": "L6V 4K2",
    "phone": "+1 555 1023",
    "email": "brampton.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 43.7121,
    "longitude": -79.7712,
    "status": "ACTIVE"
  },
  {
    "id": "store-024",
    "regionId": "region-can",
    "code": "WAL-CAN-024",
    "name": "Walmart Halifax Bayers Lake",
    "address": "220 Chain Lake Dr",
    "city": "Halifax",
    "state": "Nova Scotia",
    "country": "Canada",
    "pincode": "B3S 1C5",
    "phone": "+1 555 1024",
    "email": "halifax.store@walmart.com",
    "image": "/images/stores/store-can.webp",
    "latitude": 44.6467,
    "longitude": -63.6712,
    "status": "ACTIVE"
  },
  {
    "id": "store-025",
    "regionId": "region-gbr",
    "code": "WAL-GBR-025",
    "name": "Walmart London Oxford Street",
    "address": "120 Oxford St",
    "city": "London",
    "state": "Greater London",
    "country": "United Kingdom",
    "pincode": "W1D 1BS",
    "phone": "+44 555 1025",
    "email": "london.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 51.5161,
    "longitude": -0.1362,
    "status": "ACTIVE"
  },
  {
    "id": "store-026",
    "regionId": "region-gbr",
    "code": "WAL-GBR-026",
    "name": "Walmart Manchester Trafford",
    "address": "Trafford Centre, Regent Cres",
    "city": "Manchester",
    "state": "Greater Manchester",
    "country": "United Kingdom",
    "pincode": "M17 8AA",
    "phone": "+44 555 1026",
    "email": "manchester.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 53.4667,
    "longitude": -2.3489,
    "status": "ACTIVE"
  },
  {
    "id": "store-027",
    "regionId": "region-gbr",
    "code": "WAL-GBR-027",
    "name": "Walmart Birmingham Central",
    "address": "Bullring Shopping Centre",
    "city": "Birmingham",
    "state": "West Midlands",
    "country": "United Kingdom",
    "pincode": "B5 4BU",
    "phone": "+44 555 1027",
    "email": "birmingham.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 52.4776,
    "longitude": -1.8936,
    "status": "ACTIVE"
  },
  {
    "id": "store-028",
    "regionId": "region-gbr",
    "code": "WAL-GBR-028",
    "name": "Walmart Leeds Briggate",
    "address": "Trinity Leeds, Albion St",
    "city": "Leeds",
    "state": "West Yorkshire",
    "country": "United Kingdom",
    "pincode": "LS1 5AT",
    "phone": "+44 555 1028",
    "email": "leeds.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 53.7972,
    "longitude": -1.5451,
    "status": "ACTIVE"
  },
  {
    "id": "store-029",
    "regionId": "region-gbr",
    "code": "WAL-GBR-029",
    "name": "Walmart Glasgow Fort",
    "address": "Provan Walk, Glasgow Fort",
    "city": "Glasgow",
    "state": "Scotland",
    "country": "United Kingdom",
    "pincode": "G34 9DL",
    "phone": "+44 555 1029",
    "email": "glasgow.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 55.8677,
    "longitude": -4.1378,
    "status": "ACTIVE"
  },
  {
    "id": "store-030",
    "regionId": "region-gbr",
    "code": "WAL-GBR-030",
    "name": "Walmart Edinburgh Princes",
    "address": "Princes St, City Centre",
    "city": "Edinburgh",
    "state": "Scotland",
    "country": "United Kingdom",
    "pincode": "EH2 2EQ",
    "phone": "+44 555 1030",
    "email": "edinburgh.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 55.9521,
    "longitude": -3.1965,
    "status": "ACTIVE"
  },
  {
    "id": "store-031",
    "regionId": "region-gbr",
    "code": "WAL-GBR-031",
    "name": "Walmart Liverpool One",
    "address": "5 Wall St, Liverpool One",
    "city": "Liverpool",
    "state": "Merseyside",
    "country": "United Kingdom",
    "pincode": "L1 8JQ",
    "phone": "+44 555 1031",
    "email": "liverpool.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 53.4034,
    "longitude": -2.9867,
    "status": "ACTIVE"
  },
  {
    "id": "store-032",
    "regionId": "region-gbr",
    "code": "WAL-GBR-032",
    "name": "Walmart Bristol Cribbs",
    "address": "Cribbs Causeway",
    "city": "Bristol",
    "state": "South West",
    "country": "United Kingdom",
    "pincode": "BS34 5DG",
    "phone": "+44 555 1032",
    "email": "bristol.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 51.5256,
    "longitude": -2.5978,
    "status": "ACTIVE"
  },
  {
    "id": "store-033",
    "regionId": "region-gbr",
    "code": "WAL-GBR-033",
    "name": "Walmart Sheffield Meadowhall",
    "address": "Meadowhall Way",
    "city": "Sheffield",
    "state": "South Yorkshire",
    "country": "United Kingdom",
    "pincode": "S9 1EP",
    "phone": "+44 555 1033",
    "email": "sheffield.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 53.4144,
    "longitude": -1.4112,
    "status": "ACTIVE"
  },
  {
    "id": "store-034",
    "regionId": "region-gbr",
    "code": "WAL-GBR-034",
    "name": "Walmart Newcastle Eldon",
    "address": "Eldon Square",
    "city": "Newcastle",
    "state": "Tyne and Wear",
    "country": "United Kingdom",
    "pincode": "NE1 7JB",
    "phone": "+44 555 1034",
    "email": "newcastle.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 54.9752,
    "longitude": -1.6152,
    "status": "ACTIVE"
  },
  {
    "id": "store-035",
    "regionId": "region-gbr",
    "code": "WAL-GBR-035",
    "name": "Walmart Belfast Victoria",
    "address": "Victoria Square",
    "city": "Belfast",
    "state": "Northern Ireland",
    "country": "United Kingdom",
    "pincode": "BT1 4QG",
    "phone": "+44 555 1035",
    "email": "belfast.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 54.5982,
    "longitude": -5.9254,
    "status": "ACTIVE"
  },
  {
    "id": "store-036",
    "regionId": "region-gbr",
    "code": "WAL-GBR-036",
    "name": "Walmart Cardiff Bay",
    "address": "Queen St, City Centre",
    "city": "Cardiff",
    "state": "Wales",
    "country": "United Kingdom",
    "pincode": "CF10 2AQ",
    "phone": "+44 555 1036",
    "email": "cardiff.store@walmart.com",
    "image": "/images/stores/store-gbr.webp",
    "latitude": 51.4821,
    "longitude": -3.1764,
    "status": "ACTIVE"
  },
  {
    "id": "store-037",
    "regionId": "region-deu",
    "code": "WAL-DEU-037",
    "name": "Walmart Berlin Alexanderplatz",
    "address": "Alexanderplatz 9",
    "city": "Berlin",
    "state": "Berlin",
    "country": "Germany",
    "pincode": "10178",
    "phone": "+49 555 1037",
    "email": "berlin.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 52.5219,
    "longitude": 13.4132,
    "status": "ACTIVE"
  },
  {
    "id": "store-038",
    "regionId": "region-deu",
    "code": "WAL-DEU-038",
    "name": "Walmart Munich Marienplatz",
    "address": "Kaufingerstrasse 24",
    "city": "Munich",
    "state": "Bavaria",
    "country": "Germany",
    "pincode": "80331",
    "phone": "+49 555 1038",
    "email": "munich.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 48.1372,
    "longitude": 11.5755,
    "status": "ACTIVE"
  },
  {
    "id": "store-039",
    "regionId": "region-deu",
    "code": "WAL-DEU-039",
    "name": "Walmart Frankfurt Zeil",
    "address": "Zeil 106",
    "city": "Frankfurt",
    "state": "Hesse",
    "country": "Germany",
    "pincode": "60313",
    "phone": "+49 555 1039",
    "email": "frankfurt.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 50.1147,
    "longitude": 8.6865,
    "status": "ACTIVE"
  },
  {
    "id": "store-040",
    "regionId": "region-deu",
    "code": "WAL-DEU-040",
    "name": "Walmart Hamburg Jungfernstieg",
    "address": "Jungfernstieg 16",
    "city": "Hamburg",
    "state": "Hamburg",
    "country": "Germany",
    "pincode": "20354",
    "phone": "+49 555 1040",
    "email": "hamburg.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 53.5534,
    "longitude": 9.9921,
    "status": "ACTIVE"
  },
  {
    "id": "store-041",
    "regionId": "region-deu",
    "code": "WAL-DEU-041",
    "name": "Walmart Cologne Neumarkt",
    "address": "Schildergasse 84",
    "city": "Cologne",
    "state": "North Rhine-Westphalia",
    "country": "Germany",
    "pincode": "50667",
    "phone": "+49 555 1041",
    "email": "cologne.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 50.9365,
    "longitude": 6.9532,
    "status": "ACTIVE"
  },
  {
    "id": "store-042",
    "regionId": "region-deu",
    "code": "WAL-DEU-042",
    "name": "Walmart Stuttgart Konigstrasse",
    "address": "Konigstrasse 42",
    "city": "Stuttgart",
    "state": "Baden-Wurttemberg",
    "country": "Germany",
    "pincode": "70173",
    "phone": "+49 555 1042",
    "email": "stuttgart.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 48.7789,
    "longitude": 9.1798,
    "status": "ACTIVE"
  },
  {
    "id": "store-043",
    "regionId": "region-deu",
    "code": "WAL-DEU-043",
    "name": "Walmart Dusseldorf Schadow",
    "address": "Schadowstrasse 78",
    "city": "Dusseldorf",
    "state": "North Rhine-Westphalia",
    "country": "Germany",
    "pincode": "40212",
    "phone": "+49 555 1043",
    "email": "dusseldorf.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 51.2267,
    "longitude": 6.7845,
    "status": "ACTIVE"
  },
  {
    "id": "store-044",
    "regionId": "region-deu",
    "code": "WAL-DEU-044",
    "name": "Walmart Leipzig Hauptbahnhof",
    "address": "Willy-Brandt-Platz 7",
    "city": "Leipzig",
    "state": "Saxony",
    "country": "Germany",
    "pincode": "04109",
    "phone": "+49 555 1044",
    "email": "leipzig.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 51.3452,
    "longitude": 12.3812,
    "status": "ACTIVE"
  },
  {
    "id": "store-045",
    "regionId": "region-deu",
    "code": "WAL-DEU-045",
    "name": "Walmart Dortmund Westenhellweg",
    "address": "Westenhellweg 102",
    "city": "Dortmund",
    "state": "North Rhine-Westphalia",
    "country": "Germany",
    "pincode": "44137",
    "phone": "+49 555 1045",
    "email": "dortmund.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 51.5142,
    "longitude": 7.4612,
    "status": "ACTIVE"
  },
  {
    "id": "store-046",
    "regionId": "region-deu",
    "code": "WAL-DEU-046",
    "name": "Walmart Essen Limbecker",
    "address": "Limbecker Platz 1",
    "city": "Essen",
    "state": "North Rhine-Westphalia",
    "country": "Germany",
    "pincode": "45127",
    "phone": "+49 555 1046",
    "email": "essen.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 51.4589,
    "longitude": 7.0067,
    "status": "ACTIVE"
  },
  {
    "id": "store-047",
    "regionId": "region-deu",
    "code": "WAL-DEU-047",
    "name": "Walmart Bremen Roland",
    "address": "Obernstrasse 55",
    "city": "Bremen",
    "state": "Bremen",
    "country": "Germany",
    "pincode": "28195",
    "phone": "+49 555 1047",
    "email": "bremen.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 53.0765,
    "longitude": 8.8054,
    "status": "ACTIVE"
  },
  {
    "id": "store-048",
    "regionId": "region-deu",
    "code": "WAL-DEU-048",
    "name": "Walmart Dresden Altmarkt",
    "address": "Altmarkt 25",
    "city": "Dresden",
    "state": "Saxony",
    "country": "Germany",
    "pincode": "01067",
    "phone": "+49 555 1048",
    "email": "dresden.store@walmart.com",
    "image": "/images/stores/store-deu.webp",
    "latitude": 51.0498,
    "longitude": 13.7378,
    "status": "ACTIVE"
  },
  {
    "id": "store-049",
    "regionId": "region-jpn",
    "code": "WAL-JPN-049",
    "name": "Walmart Tokyo Shinjuku Central",
    "address": "3-38-1 Shinjuku",
    "city": "Tokyo",
    "state": "Kanto",
    "country": "Japan",
    "pincode": "160-0022",
    "phone": "+81 555 1049",
    "email": "tokyo.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 35.6909,
    "longitude": 139.7003,
    "status": "ACTIVE"
  },
  {
    "id": "store-050",
    "regionId": "region-jpn",
    "code": "WAL-JPN-050",
    "name": "Walmart Osaka Umeda",
    "address": "1-1 Umeda, Kita Ward",
    "city": "Osaka",
    "state": "Kansai",
    "country": "Japan",
    "pincode": "530-0001",
    "phone": "+81 555 1050",
    "email": "osaka.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 34.7025,
    "longitude": 135.4959,
    "status": "ACTIVE"
  },
  {
    "id": "store-051",
    "regionId": "region-jpn",
    "code": "WAL-JPN-051",
    "name": "Walmart Yokohama Minato Mirai",
    "address": "2-3-2 Minatomirai",
    "city": "Yokohama",
    "state": "Kanagawa",
    "country": "Japan",
    "pincode": "220-0012",
    "phone": "+81 555 1051",
    "email": "yokohama.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 35.4578,
    "longitude": 139.6324,
    "status": "ACTIVE"
  },
  {
    "id": "store-052",
    "regionId": "region-jpn",
    "code": "WAL-JPN-052",
    "name": "Walmart Nagoya Sakae",
    "address": "3-5-1 Sakae, Naka Ward",
    "city": "Nagoya",
    "state": "Aichi",
    "country": "Japan",
    "pincode": "460-0008",
    "phone": "+81 555 1052",
    "email": "nagoya.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 35.1681,
    "longitude": 136.9082,
    "status": "ACTIVE"
  },
  {
    "id": "store-053",
    "regionId": "region-jpn",
    "code": "WAL-JPN-053",
    "name": "Walmart Sapporo Odori",
    "address": "4 Chome Odorinishi",
    "city": "Sapporo",
    "state": "Hokkaido",
    "country": "Japan",
    "pincode": "060-0042",
    "phone": "+81 555 1053",
    "email": "sapporo.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 43.0601,
    "longitude": 141.3533,
    "status": "ACTIVE"
  },
  {
    "id": "store-054",
    "regionId": "region-jpn",
    "code": "WAL-JPN-054",
    "name": "Walmart Fukuoka Tenjin",
    "address": "2-11-3 Tenjin, Chuo Ward",
    "city": "Fukuoka",
    "state": "Kyushu",
    "country": "Japan",
    "pincode": "810-0001",
    "phone": "+81 555 1054",
    "email": "fukuoka.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 33.5902,
    "longitude": 130.3989,
    "status": "ACTIVE"
  },
  {
    "id": "store-055",
    "regionId": "region-jpn",
    "code": "WAL-JPN-055",
    "name": "Walmart Kobe Sannomiya",
    "address": "7-1-1 Onoedori, Chuo Ward",
    "city": "Kobe",
    "state": "Hyogo",
    "country": "Japan",
    "pincode": "651-0088",
    "phone": "+81 555 1055",
    "email": "kobe.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 34.6937,
    "longitude": 135.1955,
    "status": "ACTIVE"
  },
  {
    "id": "store-056",
    "regionId": "region-jpn",
    "code": "WAL-JPN-056",
    "name": "Walmart Kyoto Shijo Kawaramachi",
    "address": "Shijo-dori, Shimogyo Ward",
    "city": "Kyoto",
    "state": "Kansai",
    "country": "Japan",
    "pincode": "600-8001",
    "phone": "+81 555 1056",
    "email": "kyoto.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 35.0037,
    "longitude": 135.7687,
    "status": "ACTIVE"
  },
  {
    "id": "store-057",
    "regionId": "region-jpn",
    "code": "WAL-JPN-057",
    "name": "Walmart Kawasaki Lazona",
    "address": "72-1 Horikawacho, Saiwai Ward",
    "city": "Kawasaki",
    "state": "Kanagawa",
    "country": "Japan",
    "pincode": "212-8576",
    "phone": "+81 555 1057",
    "email": "kawasaki.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 35.5322,
    "longitude": 139.6974,
    "status": "ACTIVE"
  },
  {
    "id": "store-058",
    "regionId": "region-jpn",
    "code": "WAL-JPN-058",
    "name": "Walmart Saitama Omiya",
    "address": "1-6-2 Kishikicho, Omiya Ward",
    "city": "Saitama",
    "state": "Kanto",
    "country": "Japan",
    "pincode": "330-0843",
    "phone": "+81 555 1058",
    "email": "saitama.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 35.9063,
    "longitude": 139.6241,
    "status": "ACTIVE"
  },
  {
    "id": "store-059",
    "regionId": "region-jpn",
    "code": "WAL-JPN-059",
    "name": "Walmart Hiroshima Hatchobori",
    "address": "1-1 Hatchobori, Naka Ward",
    "city": "Hiroshima",
    "state": "Chugoku",
    "country": "Japan",
    "pincode": "730-0013",
    "phone": "+81 555 1059",
    "email": "hiroshima.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 34.3945,
    "longitude": 132.4641,
    "status": "ACTIVE"
  },
  {
    "id": "store-060",
    "regionId": "region-jpn",
    "code": "WAL-JPN-060",
    "name": "Walmart Sendai Aoba",
    "address": "1-1-1 Chuo, Aoba Ward",
    "city": "Sendai",
    "state": "Tohoku",
    "country": "Japan",
    "pincode": "980-0021",
    "phone": "+81 555 1060",
    "email": "sendai.store@walmart.com",
    "image": "/images/stores/store-jpn.webp",
    "latitude": 38.2603,
    "longitude": 140.8824,
    "status": "ACTIVE"
  },
  {
    "id": "store-061",
    "regionId": "region-ind",
    "code": "WAL-IND-061",
    "name": "Walmart Delhi Connaught Place",
    "address": "Block A, Connaught Place",
    "city": "Delhi",
    "state": "Delhi",
    "country": "India",
    "pincode": "110001",
    "phone": "+91 555 1061",
    "email": "delhi.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 28.6315,
    "longitude": 77.2167,
    "status": "ACTIVE"
  },
  {
    "id": "store-062",
    "regionId": "region-ind",
    "code": "WAL-IND-062",
    "name": "Walmart Mumbai Andheri West",
    "address": "Link Road, Andheri West",
    "city": "Mumbai",
    "state": "Maharashtra",
    "country": "India",
    "pincode": "400053",
    "phone": "+91 555 1062",
    "email": "mumbai.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 19.1363,
    "longitude": 72.8277,
    "status": "ACTIVE"
  },
  {
    "id": "store-063",
    "regionId": "region-ind",
    "code": "WAL-IND-063",
    "name": "Walmart Bangalore Koramangala",
    "address": "80 Feet Rd, Koramangala",
    "city": "Bangalore",
    "state": "Karnataka",
    "country": "India",
    "pincode": "560034",
    "phone": "+91 555 1063",
    "email": "bangalore.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 12.9352,
    "longitude": 77.6245,
    "status": "ACTIVE"
  },
  {
    "id": "store-064",
    "regionId": "region-ind",
    "code": "WAL-IND-064",
    "name": "Walmart Hyderabad Hitec City",
    "address": "Cyber Towers Rd, Hitec City",
    "city": "Hyderabad",
    "state": "Telangana",
    "country": "India",
    "pincode": "500081",
    "phone": "+91 555 1064",
    "email": "hyderabad.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 17.4474,
    "longitude": 78.3762,
    "status": "ACTIVE"
  },
  {
    "id": "store-065",
    "regionId": "region-ind",
    "code": "WAL-IND-065",
    "name": "Walmart Chennai T Nagar",
    "address": "Usman Rd, T Nagar",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "country": "India",
    "pincode": "600017",
    "phone": "+91 555 1065",
    "email": "chennai.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 13.0418,
    "longitude": 80.2341,
    "status": "ACTIVE"
  },
  {
    "id": "store-066",
    "regionId": "region-ind",
    "code": "WAL-IND-066",
    "name": "Walmart Kolkata Park Street",
    "address": "Park St, Near Flury's",
    "city": "Kolkata",
    "state": "West Bengal",
    "country": "India",
    "pincode": "700016",
    "phone": "+91 555 1066",
    "email": "kolkata.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 22.5512,
    "longitude": 88.3526,
    "status": "ACTIVE"
  },
  {
    "id": "store-067",
    "regionId": "region-ind",
    "code": "WAL-IND-067",
    "name": "Walmart Pune FC Road",
    "address": "FC Rd, Shivajinagar",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "pincode": "411005",
    "phone": "+91 555 1067",
    "email": "pune.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 18.5284,
    "longitude": 73.8443,
    "status": "ACTIVE"
  },
  {
    "id": "store-068",
    "regionId": "region-ind",
    "code": "WAL-IND-068",
    "name": "Walmart Ahmedabad SG Highway",
    "address": "SG Highway, Bodakdev",
    "city": "Ahmedabad",
    "state": "Gujarat",
    "country": "India",
    "pincode": "380054",
    "phone": "+91 555 1068",
    "email": "ahmedabad.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 23.0338,
    "longitude": 72.5074,
    "status": "ACTIVE"
  },
  {
    "id": "store-069",
    "regionId": "region-ind",
    "code": "WAL-IND-069",
    "name": "Walmart Jaipur MI Road",
    "address": "MI Rd, Panch Batti",
    "city": "Jaipur",
    "state": "Rajasthan",
    "country": "India",
    "pincode": "302001",
    "phone": "+91 555 1069",
    "email": "jaipur.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 26.9157,
    "longitude": 75.8189,
    "status": "ACTIVE"
  },
  {
    "id": "store-070",
    "regionId": "region-ind",
    "code": "WAL-IND-070",
    "name": "Walmart Surat Ring Road",
    "address": "Ring Rd, Majura Gate",
    "city": "Surat",
    "state": "Gujarat",
    "country": "India",
    "pincode": "395002",
    "phone": "+91 555 1070",
    "email": "surat.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 21.1702,
    "longitude": 72.8311,
    "status": "ACTIVE"
  },
  {
    "id": "store-071",
    "regionId": "region-ind",
    "code": "WAL-IND-071",
    "name": "Walmart Lucknow Hazratganj",
    "address": "MG Marg, Hazratganj",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "country": "India",
    "pincode": "226001",
    "phone": "+91 555 1071",
    "email": "lucknow.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 26.8467,
    "longitude": 80.9462,
    "status": "ACTIVE"
  },
  {
    "id": "store-072",
    "regionId": "region-ind",
    "code": "WAL-IND-072",
    "name": "Walmart Chandigarh Sector 17",
    "address": "Sector 17 Plaza",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "country": "India",
    "pincode": "160017",
    "phone": "+91 555 1072",
    "email": "chandigarh.store@walmart.com",
    "image": "/images/stores/store-ind.webp",
    "latitude": 30.7398,
    "longitude": 76.7827,
    "status": "ACTIVE"
  },
  {
    "id": "store-073",
    "regionId": "region-mex",
    "code": "WAL-MEX-073",
    "name": "Walmart Mexico City Polanco",
    "address": "Av Horacio 1844, Polanco",
    "city": "Mexico City",
    "state": "CDMX",
    "country": "Mexico",
    "pincode": "11560",
    "phone": "+52 555 1073",
    "email": "mexicocity.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 19.4342,
    "longitude": -99.2045,
    "status": "ACTIVE"
  },
  {
    "id": "store-074",
    "regionId": "region-mex",
    "code": "WAL-MEX-074",
    "name": "Walmart Guadalajara Zapopan",
    "address": "Av Vallarta 5145",
    "city": "Guadalajara",
    "state": "Jalisco",
    "country": "Mexico",
    "pincode": "45010",
    "phone": "+52 555 1074",
    "email": "guadalajara.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 20.6765,
    "longitude": -103.4121,
    "status": "ACTIVE"
  },
  {
    "id": "store-075",
    "regionId": "region-mex",
    "code": "WAL-MEX-075",
    "name": "Walmart Monterrey San Pedro",
    "address": "Av Vasconcelos 401",
    "city": "Monterrey",
    "state": "Nuevo Leon",
    "country": "Mexico",
    "pincode": "66220",
    "phone": "+52 555 1075",
    "email": "monterrey.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 25.6578,
    "longitude": -100.3689,
    "status": "ACTIVE"
  },
  {
    "id": "store-076",
    "regionId": "region-mex",
    "code": "WAL-MEX-076",
    "name": "Walmart Puebla Angelopolis",
    "address": "Blvd Atlixcayotl 1910",
    "city": "Puebla",
    "state": "Puebla",
    "country": "Mexico",
    "pincode": "72197",
    "phone": "+52 555 1076",
    "email": "puebla.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 19.0312,
    "longitude": -98.2321,
    "status": "ACTIVE"
  },
  {
    "id": "store-077",
    "regionId": "region-mex",
    "code": "WAL-MEX-077",
    "name": "Walmart Tijuana Rio",
    "address": "Paseo de los Heroes 95",
    "city": "Tijuana",
    "state": "Baja California",
    "country": "Mexico",
    "pincode": "22010",
    "phone": "+52 555 1077",
    "email": "tijuana.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 32.5289,
    "longitude": -117.0212,
    "status": "ACTIVE"
  },
  {
    "id": "store-078",
    "regionId": "region-mex",
    "code": "WAL-MEX-078",
    "name": "Walmart Leon Plaza Mayor",
    "address": "Av Juan Alonso de Torres 2002",
    "city": "Leon",
    "state": "Guanajuato",
    "country": "Mexico",
    "pincode": "37160",
    "phone": "+52 555 1078",
    "email": "leon.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 21.1567,
    "longitude": -101.6912,
    "status": "ACTIVE"
  },
  {
    "id": "store-079",
    "regionId": "region-mex",
    "code": "WAL-MEX-079",
    "name": "Walmart Juarez Misiones",
    "address": "Paseo de la Victoria 4450",
    "city": "Ciudad Juarez",
    "state": "Chihuahua",
    "country": "Mexico",
    "pincode": "32543",
    "phone": "+52 555 1079",
    "email": "ciudadjuarez.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 31.6872,
    "longitude": -106.3982,
    "status": "ACTIVE"
  },
  {
    "id": "store-080",
    "regionId": "region-mex",
    "code": "WAL-MEX-080",
    "name": "Walmart Cancun Kukulcan",
    "address": "Blvd Kukulcan Km 13",
    "city": "Cancun",
    "state": "Quintana Roo",
    "country": "Mexico",
    "pincode": "77500",
    "phone": "+52 555 1080",
    "email": "cancun.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 21.1098,
    "longitude": -86.7645,
    "status": "ACTIVE"
  },
  {
    "id": "store-081",
    "regionId": "region-mex",
    "code": "WAL-MEX-081",
    "name": "Walmart Merida Altabrisa",
    "address": "Calle 7 No 451, Altabrisa",
    "city": "Merida",
    "state": "Yucatan",
    "country": "Mexico",
    "pincode": "97130",
    "phone": "+52 555 1081",
    "email": "merida.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 20.9982,
    "longitude": -89.5876,
    "status": "ACTIVE"
  },
  {
    "id": "store-082",
    "regionId": "region-mex",
    "code": "WAL-MEX-082",
    "name": "Walmart Queretaro Antea",
    "address": "Carretera Qro-SLP 12401",
    "city": "Queretaro",
    "state": "Queretaro",
    "country": "Mexico",
    "pincode": "76127",
    "phone": "+52 555 1082",
    "email": "queretaro.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 20.6845,
    "longitude": -100.4378,
    "status": "ACTIVE"
  },
  {
    "id": "store-083",
    "regionId": "region-mex",
    "code": "WAL-MEX-083",
    "name": "Walmart SLP Tangamanga",
    "address": "Av Salvador Nava 100",
    "city": "San Luis Potosi",
    "state": "San Luis Potosi",
    "country": "Mexico",
    "pincode": "78280",
    "phone": "+52 555 1083",
    "email": "sanluispotosi.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 22.1432,
    "longitude": -100.9945,
    "status": "ACTIVE"
  },
  {
    "id": "store-084",
    "regionId": "region-mex",
    "code": "WAL-MEX-084",
    "name": "Walmart Toluca Metepec",
    "address": "Pino Suarez 1200",
    "city": "Toluca",
    "state": "Estado de Mexico",
    "country": "Mexico",
    "pincode": "52140",
    "phone": "+52 555 1084",
    "email": "toluca.store@walmart.com",
    "image": "/images/stores/store-mex.webp",
    "latitude": 19.2612,
    "longitude": -99.6389,
    "status": "ACTIVE"
  },
  {
    "id": "store-085",
    "regionId": "region-chn",
    "code": "WAL-CHN-085",
    "name": "Walmart Shanghai Pudong Center",
    "address": "Lujiazui Ring Rd",
    "city": "Shanghai",
    "state": "Shanghai",
    "country": "China",
    "pincode": "200120",
    "phone": "+86 555 1085",
    "email": "shanghai.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 31.2397,
    "longitude": 121.4998,
    "status": "ACTIVE"
  },
  {
    "id": "store-086",
    "regionId": "region-chn",
    "code": "WAL-CHN-086",
    "name": "Walmart Beijing Chaoyang Hub",
    "address": "Jianguo Rd, Chaoyang",
    "city": "Beijing",
    "state": "Beijing",
    "country": "China",
    "pincode": "100022",
    "phone": "+86 555 1086",
    "email": "beijing.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 39.9075,
    "longitude": 116.4678,
    "status": "ACTIVE"
  },
  {
    "id": "store-087",
    "regionId": "region-chn",
    "code": "WAL-CHN-087",
    "name": "Walmart Shenzhen Futian",
    "address": "Shennan Rd, Futian",
    "city": "Shenzhen",
    "state": "Guangdong",
    "country": "China",
    "pincode": "518048",
    "phone": "+86 555 1087",
    "email": "shenzhen.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 22.5431,
    "longitude": 114.0579,
    "status": "ACTIVE"
  },
  {
    "id": "store-088",
    "regionId": "region-chn",
    "code": "WAL-CHN-088",
    "name": "Walmart Guangzhou Tianhe",
    "address": "Tianhe Rd, Tianhe",
    "city": "Guangzhou",
    "state": "Guangdong",
    "country": "China",
    "pincode": "510620",
    "phone": "+86 555 1088",
    "email": "guangzhou.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 23.1367,
    "longitude": 113.3289,
    "status": "ACTIVE"
  },
  {
    "id": "store-089",
    "regionId": "region-chn",
    "code": "WAL-CHN-089",
    "name": "Walmart Chengdu Chunxi",
    "address": "Chunxi Rd, Jinjiang",
    "city": "Chengdu",
    "state": "Sichuan",
    "country": "China",
    "pincode": "610016",
    "phone": "+86 555 1089",
    "email": "chengdu.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 30.6586,
    "longitude": 104.0812,
    "status": "ACTIVE"
  },
  {
    "id": "store-090",
    "regionId": "region-chn",
    "code": "WAL-CHN-090",
    "name": "Walmart Hangzhou Xihu",
    "address": "Yan'an Rd, Xihu",
    "city": "Hangzhou",
    "state": "Zhejiang",
    "country": "China",
    "pincode": "310006",
    "phone": "+86 555 1090",
    "email": "hangzhou.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 30.2598,
    "longitude": 120.1623,
    "status": "ACTIVE"
  },
  {
    "id": "store-091",
    "regionId": "region-chn",
    "code": "WAL-CHN-091",
    "name": "Walmart Wuhan Jianghan",
    "address": "Zhongshan Ave, Jianghan",
    "city": "Wuhan",
    "state": "Hubei",
    "country": "China",
    "pincode": "430022",
    "phone": "+86 555 1091",
    "email": "wuhan.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 30.5842,
    "longitude": 114.2812,
    "status": "ACTIVE"
  },
  {
    "id": "store-092",
    "regionId": "region-chn",
    "code": "WAL-CHN-092",
    "name": "Walmart Xi'an Zhonglou",
    "address": "South St, Beilin",
    "city": "Xi'an",
    "state": "Shaanxi",
    "country": "China",
    "pincode": "710001",
    "phone": "+86 555 1092",
    "email": "xian.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 34.2589,
    "longitude": 108.9489,
    "status": "ACTIVE"
  },
  {
    "id": "store-093",
    "regionId": "region-chn",
    "code": "WAL-CHN-093",
    "name": "Walmart Chongqing Jiefangbei",
    "address": "Minzu Rd, Yuzhong",
    "city": "Chongqing",
    "state": "Chongqing",
    "country": "China",
    "pincode": "400010",
    "phone": "+86 555 1093",
    "email": "chongqing.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 29.5578,
    "longitude": 106.5789,
    "status": "ACTIVE"
  },
  {
    "id": "store-094",
    "regionId": "region-chn",
    "code": "WAL-CHN-094",
    "name": "Walmart Tianjin Heping",
    "address": "Nanjing Rd, Heping",
    "city": "Tianjin",
    "state": "Tianjin",
    "country": "China",
    "pincode": "300050",
    "phone": "+86 555 1094",
    "email": "tianjin.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 39.1178,
    "longitude": 117.1989,
    "status": "ACTIVE"
  },
  {
    "id": "store-095",
    "regionId": "region-chn",
    "code": "WAL-CHN-095",
    "name": "Walmart Nanjing Xinjiekou",
    "address": "Zhongshan Rd, Gulou",
    "city": "Nanjing",
    "state": "Jiangsu",
    "country": "China",
    "pincode": "210005",
    "phone": "+86 555 1095",
    "email": "nanjing.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 32.0467,
    "longitude": 118.7845,
    "status": "ACTIVE"
  },
  {
    "id": "store-096",
    "regionId": "region-chn",
    "code": "WAL-CHN-096",
    "name": "Walmart Suzhou Industrial Park",
    "address": "Suzhou Ave W, SIP",
    "city": "Suzhou",
    "state": "Jiangsu",
    "country": "China",
    "pincode": "215021",
    "phone": "+86 555 1096",
    "email": "suzhou.store@walmart.com",
    "image": "/images/stores/store-chn.webp",
    "latitude": 31.3178,
    "longitude": 120.6789,
    "status": "ACTIVE"
  },
  {
    "id": "store-097",
    "regionId": "region-bra",
    "code": "WAL-BRA-097",
    "name": "Walmart Sao Paulo Paulista",
    "address": "Av Paulista 1800",
    "city": "Sao Paulo",
    "state": "Sao Paulo",
    "country": "Brazil",
    "pincode": "01310-200",
    "phone": "+55 555 1097",
    "email": "saopaulo.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -23.5612,
    "longitude": -46.6565,
    "status": "ACTIVE"
  },
  {
    "id": "store-098",
    "regionId": "region-bra",
    "code": "WAL-BRA-098",
    "name": "Walmart Rio Barra da Tijuca",
    "address": "Av das Americas 5000",
    "city": "Rio de Janeiro",
    "state": "Rio de Janeiro",
    "country": "Brazil",
    "pincode": "22640-102",
    "phone": "+55 555 1098",
    "email": "riodejaneiro.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -22.9989,
    "longitude": -43.3645,
    "status": "ACTIVE"
  },
  {
    "id": "store-099",
    "regionId": "region-bra",
    "code": "WAL-BRA-099",
    "name": "Walmart Brasilia Asa Sul",
    "address": "SHCS CLS 404",
    "city": "Brasilia",
    "state": "Distrito Federal",
    "country": "Brazil",
    "pincode": "70238-510",
    "phone": "+55 555 1099",
    "email": "brasilia.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -15.8142,
    "longitude": -47.9012,
    "status": "ACTIVE"
  },
  {
    "id": "store-100",
    "regionId": "region-bra",
    "code": "WAL-BRA-100",
    "name": "Walmart Salvador Barra",
    "address": "Av Centenario 2992",
    "city": "Salvador",
    "state": "Bahia",
    "country": "Brazil",
    "pincode": "40155-150",
    "phone": "+55 555 1100",
    "email": "salvador.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -13.0034,
    "longitude": -38.5289,
    "status": "ACTIVE"
  },
  {
    "id": "store-101",
    "regionId": "region-bra",
    "code": "WAL-BRA-101",
    "name": "Walmart Fortaleza Aldeota",
    "address": "Av Santos Dumont 3131",
    "city": "Fortaleza",
    "state": "Ceara",
    "country": "Brazil",
    "pincode": "60150-162",
    "phone": "+55 555 1101",
    "email": "fortaleza.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -3.7389,
    "longitude": -38.4982,
    "status": "ACTIVE"
  },
  {
    "id": "store-102",
    "regionId": "region-bra",
    "code": "WAL-BRA-102",
    "name": "Walmart Belo Horizonte Savassi",
    "address": "Av Cristovao Colombo 519",
    "city": "Belo Horizonte",
    "state": "Minas Gerais",
    "country": "Brazil",
    "pincode": "30140-150",
    "phone": "+55 555 1102",
    "email": "belohorizonte.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -19.9389,
    "longitude": -43.9367,
    "status": "ACTIVE"
  },
  {
    "id": "store-103",
    "regionId": "region-bra",
    "code": "WAL-BRA-103",
    "name": "Walmart Curitiba Batel",
    "address": "Av do Batel 1868",
    "city": "Curitiba",
    "state": "Parana",
    "country": "Brazil",
    "pincode": "80420-090",
    "phone": "+55 555 1103",
    "email": "curitiba.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -25.4421,
    "longitude": -49.2891,
    "status": "ACTIVE"
  },
  {
    "id": "store-104",
    "regionId": "region-bra",
    "code": "WAL-BRA-104",
    "name": "Walmart Recife Boa Viagem",
    "address": "Av Conselheiro Aguiar 4000",
    "city": "Recife",
    "state": "Pernambuco",
    "country": "Brazil",
    "pincode": "51021-020",
    "phone": "+55 555 1104",
    "email": "recife.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -8.1212,
    "longitude": -34.9012,
    "status": "ACTIVE"
  },
  {
    "id": "store-105",
    "regionId": "region-bra",
    "code": "WAL-BRA-105",
    "name": "Walmart Porto Alegre Moinhos",
    "address": "Rua Padre Chagas 300",
    "city": "Porto Alegre",
    "state": "Rio Grande do Sul",
    "country": "Brazil",
    "pincode": "90570-080",
    "phone": "+55 555 1105",
    "email": "portoalegre.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -30.0267,
    "longitude": -51.2045,
    "status": "ACTIVE"
  },
  {
    "id": "store-106",
    "regionId": "region-bra",
    "code": "WAL-BRA-106",
    "name": "Walmart Manaus Ponta Negra",
    "address": "Av Coronel Teixeira 5705",
    "city": "Manaus",
    "state": "Amazonas",
    "country": "Brazil",
    "pincode": "69037-000",
    "phone": "+55 555 1106",
    "email": "manaus.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -3.0789,
    "longitude": -60.0712,
    "status": "ACTIVE"
  },
  {
    "id": "store-107",
    "regionId": "region-bra",
    "code": "WAL-BRA-107",
    "name": "Walmart Campinas Cambui",
    "address": "Rua Coronel Quirino 1100",
    "city": "Campinas",
    "state": "Sao Paulo",
    "country": "Brazil",
    "pincode": "13025-002",
    "phone": "+55 555 1107",
    "email": "campinas.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -22.8989,
    "longitude": -47.0543,
    "status": "ACTIVE"
  },
  {
    "id": "store-108",
    "regionId": "region-bra",
    "code": "WAL-BRA-108",
    "name": "Walmart Goiania Bueno",
    "address": "Av T-10, Setor Bueno",
    "city": "Goiania",
    "state": "Goias",
    "country": "Brazil",
    "pincode": "74223-060",
    "phone": "+55 555 1108",
    "email": "goiania.store@walmart.com",
    "image": "/images/stores/store-bra.webp",
    "latitude": -16.7112,
    "longitude": -49.2689,
    "status": "ACTIVE"
  },
  {
    "id": "store-109",
    "regionId": "region-aus",
    "code": "WAL-AUS-109",
    "name": "Walmart Sydney George Street",
    "address": "400 George St",
    "city": "Sydney",
    "state": "New South Wales",
    "country": "Australia",
    "pincode": "2000",
    "phone": "+61 555 1109",
    "email": "sydney.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -33.8698,
    "longitude": 151.2078,
    "status": "ACTIVE"
  },
  {
    "id": "store-110",
    "regionId": "region-aus",
    "code": "WAL-AUS-110",
    "name": "Walmart Melbourne Bourke Street",
    "address": "280 Bourke St Mall",
    "city": "Melbourne",
    "state": "Victoria",
    "country": "Australia",
    "pincode": "3000",
    "phone": "+61 555 1110",
    "email": "melbourne.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -37.8136,
    "longitude": 144.9654,
    "status": "ACTIVE"
  },
  {
    "id": "store-111",
    "regionId": "region-aus",
    "code": "WAL-AUS-111",
    "name": "Walmart Brisbane Queen Street",
    "address": "150 Queen St",
    "city": "Brisbane",
    "state": "Queensland",
    "country": "Australia",
    "pincode": "4000",
    "phone": "+61 555 1111",
    "email": "brisbane.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -27.4698,
    "longitude": 153.0251,
    "status": "ACTIVE"
  },
  {
    "id": "store-112",
    "regionId": "region-aus",
    "code": "WAL-AUS-112",
    "name": "Walmart Perth Hay Street",
    "address": "650 Hay St Mall",
    "city": "Perth",
    "state": "Western Australia",
    "country": "Australia",
    "pincode": "6000",
    "phone": "+61 555 1112",
    "email": "perth.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -31.9535,
    "longitude": 115.8575,
    "status": "ACTIVE"
  },
  {
    "id": "store-113",
    "regionId": "region-aus",
    "code": "WAL-AUS-113",
    "name": "Walmart Adelaide Rundle Mall",
    "address": "100 Rundle Mall",
    "city": "Adelaide",
    "state": "South Australia",
    "country": "Australia",
    "pincode": "5000",
    "phone": "+61 555 1113",
    "email": "adelaide.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -34.9228,
    "longitude": 138.6012,
    "status": "ACTIVE"
  },
  {
    "id": "store-114",
    "regionId": "region-aus",
    "code": "WAL-AUS-114",
    "name": "Walmart Gold Coast Broadbeach",
    "address": "Hooker Blvd, Pacific Fair",
    "city": "Gold Coast",
    "state": "Queensland",
    "country": "Australia",
    "pincode": "4218",
    "phone": "+61 555 1114",
    "email": "goldcoast.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -28.0367,
    "longitude": 153.4312,
    "status": "ACTIVE"
  },
  {
    "id": "store-115",
    "regionId": "region-aus",
    "code": "WAL-AUS-115",
    "name": "Walmart Canberra Civic Centre",
    "address": "Bunda St, City Centre",
    "city": "Canberra",
    "state": "ACT",
    "country": "Australia",
    "pincode": "2601",
    "phone": "+61 555 1115",
    "email": "canberra.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -35.2809,
    "longitude": 149.13,
    "status": "ACTIVE"
  },
  {
    "id": "store-116",
    "regionId": "region-aus",
    "code": "WAL-AUS-116",
    "name": "Walmart Newcastle Hunter",
    "address": "Hunter St Mall",
    "city": "Newcastle",
    "state": "New South Wales",
    "country": "Australia",
    "pincode": "2300",
    "phone": "+61 555 1116",
    "email": "newcastle.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -32.9278,
    "longitude": 151.7812,
    "status": "ACTIVE"
  },
  {
    "id": "store-117",
    "regionId": "region-aus",
    "code": "WAL-AUS-117",
    "name": "Walmart Wollongong Crown",
    "address": "200 Crown St",
    "city": "Wollongong",
    "state": "New South Wales",
    "country": "Australia",
    "pincode": "2500",
    "phone": "+61 555 1117",
    "email": "wollongong.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -34.4256,
    "longitude": 150.8945,
    "status": "ACTIVE"
  },
  {
    "id": "store-118",
    "regionId": "region-aus",
    "code": "WAL-AUS-118",
    "name": "Walmart Geelong Moorabool",
    "address": "Moorabool St, Market Square",
    "city": "Geelong",
    "state": "Victoria",
    "country": "Australia",
    "pincode": "3220",
    "phone": "+61 555 1118",
    "email": "geelong.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -38.1489,
    "longitude": 144.3612,
    "status": "ACTIVE"
  },
  {
    "id": "store-119",
    "regionId": "region-aus",
    "code": "WAL-AUS-119",
    "name": "Walmart Hobart Salamanca",
    "address": "Salamanca Pl, Waterfront",
    "city": "Hobart",
    "state": "Tasmania",
    "country": "Australia",
    "pincode": "7000",
    "phone": "+61 555 1119",
    "email": "hobart.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -42.8867,
    "longitude": 147.3321,
    "status": "ACTIVE"
  },
  {
    "id": "store-120",
    "regionId": "region-aus",
    "code": "WAL-AUS-120",
    "name": "Walmart Darwin Waterfront",
    "address": "Kitchener Dr, Waterfront",
    "city": "Darwin",
    "state": "Northern Territory",
    "country": "Australia",
    "pincode": "0800",
    "phone": "+61 555 1120",
    "email": "darwin.store@walmart.com",
    "image": "/images/stores/store-aus.webp",
    "latitude": -12.4645,
    "longitude": 130.8456,
    "status": "ACTIVE"
  }
] as const;

/** Category hierarchy — parent categories and sub-categories */
export const CATEGORIES = [
  { id: "cat-grocery", code: "GRC", name: "Groceries", parentId: null },
  { id: "cat-beverages", code: "BEV", name: "Beverages", parentId: null },
  { id: "cat-dairy", code: "DRY", name: "Dairy", parentId: null },
  { id: "cat-bakery", code: "BKY", name: "Bakery", parentId: null },
  { id: "cat-personal", code: "PRC", name: "Personal Care", parentId: null },
  { id: "cat-household", code: "HLD", name: "Household", parentId: null },
  { id: "cat-electronics", code: "ELC", name: "Electronics", parentId: null },
  { id: "cat-mobile-acc", code: "MOB", name: "Mobile Accessories", parentId: "cat-electronics" },
  { id: "cat-audio", code: "AUD", name: "Audio", parentId: "cat-electronics" },
  { id: "cat-comp-acc", code: "CMP", name: "Computer Accessories", parentId: "cat-electronics" },
  { id: "cat-appliances", code: "APL", name: "Home Appliances", parentId: null },
  { id: "cat-kitchen", code: "KTN", name: "Kitchen", parentId: null },
  { id: "cat-furniture", code: "FRN", name: "Furniture", parentId: null },
  { id: "cat-clothing", code: "CLT", name: "Clothing", parentId: null },
  { id: "cat-footwear", code: "FTW", name: "Footwear", parentId: null },
  { id: "cat-stationery", code: "STN", name: "Stationery", parentId: null },
  { id: "cat-sports", code: "SPT", name: "Sports", parentId: null },
  { id: "cat-toys", code: "TOY", name: "Toys", parentId: null },
  { id: "cat-beauty", code: "BTY", name: "Beauty", parentId: null },
  { id: "cat-petcare", code: "PET", name: "Pet Care", parentId: null },
] as const;

/** Tax rates used globally (e.g. Sales Tax / VAT) */
export const TAX_RATES = [0, 5, 8, 10, 15] as const;

/** Chart of Accounts */
export const ACCOUNTS = [
  { id: "acc-1000", code: "1000", name: "Cash", type: "ASSET" as const },
  { id: "acc-1010", code: "1010", name: "Bank", type: "ASSET" as const },
  { id: "acc-1100", code: "1100", name: "Accounts Receivable", type: "ASSET" as const },
  { id: "acc-1200", code: "1200", name: "Inventory", type: "ASSET" as const },
  { id: "acc-1300", code: "1300", name: "Input Tax Credit", type: "ASSET" as const },
  { id: "acc-2000", code: "2000", name: "Accounts Payable", type: "LIABILITY" as const },
  { id: "acc-2100", code: "2100", name: "Tax Payable", type: "LIABILITY" as const },
  { id: "acc-3000", code: "3000", name: "Owner Equity", type: "EQUITY" as const },
  { id: "acc-4000", code: "4000", name: "Sales Revenue", type: "REVENUE" as const },
  { id: "acc-4100", code: "4100", name: "Sales Discount", type: "EXPENSE" as const },
  { id: "acc-5000", code: "5000", name: "Cost of Goods Sold", type: "EXPENSE" as const },
  { id: "acc-5100", code: "5100", name: "Purchase Expense", type: "EXPENSE" as const },
] as const;
